### ISSUE TITLE
No such file/directory - docker ov_maplab

### ISSUE THREAD

**Issue by Aishkrish18** [rpng/ov_maplab#11]
![Screenshot from 2023-08-23 15-54-03](https://github.com/rpng/ov_maplab/assets/47241581/b97ba1e8-a474-42d0-b9d3-6948a8846a2e)

I am not sure why / how this error is coming up. I cloned into the submodules as per instructions. I can't see the corresponding compose file to check what is wrong, may i know how i can fix this?

**Comment by Aishkrish18** [comment]
Sorry, i executed the command wrong, and i think the documentation needs to be updated for the command, which i blindly copied. Would be nice to change it  to `docker build -t ov_maplab -f Docker _Version  .`

**Comment by goldbattle** [comment]
True. This is due to me renaming the docker file to a custom name. Will
update this so others don't run into the problem.
You can also refer to this page if you have difficulty with docker building:
https://docs.openvins.com/dev-docker.html
