### ISSUE TITLE
Docker build failed on latest `master` branch commit of maplab

### ISSUE THREAD

**Issue by Aishkrish18** [rpng/ov_maplab#12]
![Screenshot from 2023-08-23 16-42-59](https://github.com/rpng/ov_maplab/assets/47241581/522db4d1-cec7-4aea-9da5-3c078f0db820)
![Screenshot from 2023-08-23 16-43-16](https://github.com/rpng/ov_maplab/assets/47241581/29829d00-7a02-4c6c-b9af-00971778e9d6)

Is this c ++ version problem? I am building it inside the docker. Should i install any dependency?

**Comment by Aishkrish18** [comment]
I was able to build the docker with the master branch, although i read in one of the issues that the maplab codeworks only with a particular commit . Is that still the case, or can i try it out on the master branch ? 
Second question: I would like to generate map with my own custom camera, which i use for realtime localisation with OpenVINS. Can you tell me if this is possible and where can i add these config values? Or is it important that this can only run on a bag file? 
`roslaunch ov_maplab serial.launch config:=euroc_mav dataset:=V1_02_medium` how do i modify this command for cameras running in realtime?

**Comment by goldbattle** [comment]
Can you please be specific about what commit you are using to build?
Recently I updated this to support their latest main branch. The install
guide in the readme of ov_maplab should have what specific commit I built
on (and thus is the only one this project currently supports, but maybe
newer ones can still work.).

**Comment by Aishkrish18** [comment]
Yes, I built on the /master branch of maplab, i would like to know if that can support ov_maplab, otherwise, as you have mentioned in one of the issues ,I shall stick to that specific commit you built on.  
In order for trying mapping with ZED cameras, do i have to record a dataset  and then run it as a bag file? Or is it possible that i run it realtime and simultaneously?

**Comment by goldbattle** [comment]
This repo only runs things in serial as the feature matching is done by maplab itself a second time as compared to using the feature tracking from OpenVINS. This just builds the initial trajectory / visual-inertial map that can then be imported as a standard vimap. Short answer: nothing is realtime, can only process a bag as in the readme.

Hope this helps.

**Comment by Aishkrish18** [comment]
Thank you for your reply. Sorry, to reiterate on the same topic, i just want to make few things clear: 
1. OpenVINS only supports localisation and no mapping
2. In order to generate a map, record a data set from openvins and then use it with ov_maplab 
3. In order to localise in a created map, use ROVIOLI? (does this allow mapping and localising only with ROVIO algorithm or any other localisation algorithm?)
In order to do realtime localisation and mapping is there any possible way to use openVINS and perform the same?

Thank you so much for your time and reply.

**Comment by goldbattle** [comment]
OpenVINS is an odometry method, thus doesn't use a map.
You can use OpenVINS to be the "initial guess" to systems which will do
offline optimization such as maplab.
This is what the ov_maplab project is for.

Some other algorithm would then need to be used to localize against a map,
such as the mentioned ROVIOLI.

OpenVINS is just odometry, thus will never be able to leverage a prior map.
It is a research platform, so you could try to implement this yourself on
top of it!
Hope this helps.

**Comment by goldbattle** [comment]
Conclusion is to stick to the commit I have tested on, or work through the compile errors yourself to try to get the latest to build. 


From our readme:
```bash
# setup our workspace and clone
mkdir -p catkin_ws_maplab/src/
cd catkin_ws_maplab/src/
git clone https://github.com/rpng/ov_maplab.git
git clone https://github.com/rpng/open_vins.git
git clone https://github.com/ethz-asl/maplab.git --recursive
# switch open_vins to last tested commit (might build with newer)
cd open_vins/
git checkout 4534a2f32d4763bdc8c95121b3292c7423e12aca
cd ..
# switch maplab to last tested commit (might build with newer)
cd maplab/
git checkout 0b4868efeb292851d71f98d31a1e6bb40ebb244b
git submodule update --init --recursive
cd ..
```

If you do work through the compile issues, feel free to open a PR with the fixes.
