### ISSUE TITLE
accommodate to the latest maplab framework

### ISSUE THREAD

**Issue by CanCanZeng** [rpng/ov_maplab#2]
Hi, thank you for providing this grate example for combine open_vins and maplab. But I find that in the latest maplab code, feature_tracking::VOFeatureTrackingPipeline::runTrackingAndTriangulationForAllMissions https://github.com/rpng/ov_maplab/blob/6a7ea58878a1544b84b6abc6912f828cdc97c5e9/src/mapper/MapBuilder.cpp#L225 is gone, and I do not find any other alternatives. Can you port this code to the latest maplab or give me some advice since I need to use maplab in Ubuntu20.04.

**Comment by goldbattle** [comment]
Have you been able to build maplab with 20.04?
I thought that the main branch is just 16.04, and the develop is 16.04 and 18.04.
I plan to update the readme on this repo with instructions to use Docker.

**Comment by CanCanZeng** [comment]
Yes, the develop branch can be compiled in 20.04.
What do you mean by `update the readme on this repo with instructions to use Docker` ? Without change the code but use docker in 20.04?

**Comment by goldbattle** [comment]
I have updated the project to work with the newest OpenVINS and the maplab develop branch.
Please checkout the updated readme and let me know, thanks!

**Comment by CanCanZeng** [comment]
Hi, I have tested the pipeline on the develop branch of maplab, it works! Thanks very much!
By the way, I do not run openvins online, but save the measurement of openvins and then import it to maplab, just like this issue said https://github.com/ethz-asl/maplab/issues/349, I create a map from just a measurement file(including pose, bias and time_offset).

**Comment by goldbattle** [comment]
Great glad it addressed your issue.
