### ISSUE TITLE
roslaunch ov_maplab serial.launch error

### ISSUE THREAD

**Issue by DavidJames2021** [rpng/ov_maplab#6]
when i use "roslaunch ov_maplab serial.launch"  
it get errors:
![1](https://user-images.githubusercontent.com/74865460/215977278-be4644e7-6a44-40d3-9a42-ffda0db080e8.png)

**Comment by goldbattle** [comment]
I am unable to reproduce this. Do you have the dataset this is causing troubles on? Make sure to checkout the correct version of maplab which is supported (see https://github.com/rpng/ov_maplab/issues/3#issuecomment-1553134337)

**Comment by goldbattle** [comment]
Should be fixed on the latest master which was updated for the newest version of maplab.
